language: cpp

matrix:
    include:
        - os: osx
          compiler: gcc
        - os: osx
          compiler: clang

script:
        - | 
             mkdir build
             cd build
             cmake ..
             cmake --build .
             ctest -VV
